Browser favicon and title update
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #101
Opened 2024-09-14 21:14 UTC by sandy-marrero

Updated the icon/favicon so they correctly show our project current icon. Replaces the default react icon and tab title.
![image](https://github.com/user-attachments/assets/cf0f014d-fcf9-4cee-8915-f47655532e4f)

2024-09-15 22:20 UTC, AngelCIICMorales requested changes
For simplicity, please link this pull request with your previous one.

2024-09-17 01:49 UTC, JadiellMV approved these changes
All looks good.

2024-09-17 20:58 UTC, Keiven-Soto reviewed
looks good

2024-09-17 20:58 UTC, Keiven-Soto approved these changes

2024-09-18 17:21 UTC, merged