Implemented the visibility of the rules
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #106
Opened 2024-09-17 00:20 UTC by Joaquin939

2024-09-18 17:18 UTC, AngelCIICMorales commented
Compiled with problems:
×
ERROR in ./src/App.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\Angel\Desktop\Experiment\semester-project-multiplayer-dominoes\frontend\src\App.js: Expected corresponding JSX closing tag for <header>. (52:10)

  50 |             <Route path="/game" element={<MainGame />} />
  51 |             <Route path="/lobby" element={<Lobby/>} />
> 52 |           </Routes>
     |           ^
  53 |         </header>
  54 |       </div>
  55 |     </Router>
    at constructor (C:

2024-09-18 17:19 UTC, AngelCIICMorales commented
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.

2024-09-18 17:19 UTC, AngelCIICMorales requested changes
Please add the dependencies.

2024-09-18 18:14 UTC, Joaquin939 commented
> Please add the dependencies.

Done, thank you.

2024-09-19 12:13 UTC, AngelCIICMorales requested changes
It looks good; however, you placed the button on top of the lobby button. Fix this and I'll approve.

2024-09-19 12:20 UTC, Joaquin939 commented
> It looks good; however, you placed the button on top of the lobby button. Fix this and I'll approve.

I was able to implement this quick change so that both buttons are visible thank you

2024-09-19 12:42 UTC, fernandopizarro1 reviewed
Merge the last changes so it is good to go!

2024-09-19 12:42 UTC, AngelCIICMorales requested changes
One final thing. Make sure the branch is up to date.

2024-09-19 12:47 UTC, Joaquin939 commented
> One final thing. Make sure the branch is up to date.

Done, Thank you

2024-09-19 13:05 UTC, fernandopizarro1 requested changes

2024-09-19 13:05 UTC, fernandopizarro1 commented on frontend/package.json
You forgot to delete the extra `"type": "module"` on the package.json file!

2024-09-19 13:16 UTC, fernandopizarro1 commented on frontend/package.json
Yeah its probably a merge problem most likely, at least it seems that way, because I deleted that extra line and the project ran just fine

2024-09-19 13:16 UTC, Joaquin939 commented on frontend/package.json
![image](https://github.com/user-attachments/assets/788dece7-8e48-4a9f-b054-ad487d2246ab)

This is what I see on my package.json file. Am I supposed to delete it anyways?

2024-09-19 13:17 UTC, fernandopizarro1 commented on frontend/package.json
Its on the bottom of the file

2024-09-19 13:18 UTC, fernandopizarro1 commented on frontend/package.json
![image](https://github.com/user-attachments/assets/65b11d06-94eb-424e-be01-2a541ca0aef7)

2024-09-19 13:20 UTC, Joaquin939 commented on frontend/package.json
My bad, I was looking at the wrong file. Thanks. I already fixed it.

2024-09-19 13:24 UTC, fernandopizarro1 approved these changes
LGTM!

2024-09-19 21:27 UTC, PinkSylvie commented
Ran it and it looks great! Aunque detallito de que el font no ha cambiado a el que aparecia en el wireframe

2024-09-19 21:42 UTC, Joaquin939 commented
> Ran it and it looks great! Aunque detallito de que el font no ha cambiado a el que aparecia en el wireframe

Thanks, I updated the font so it matches the wireframe.

2024-09-19 21:51 UTC, PinkSylvie approved these changes
Looks great!

2024-09-20 12:34 UTC, AngelCIICMorales approved these changes
LGTM!

2024-09-20 12:34 UTC, merged