30 - Pause screen with "Resume Game" and "Back to login" buttons.
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #107
Opened 2024-09-17 04:21 UTC by Jvstinoo

Added button to pause game which takes you to a pause screen with "Resume Game" and "Back to login" buttons.

<img width="433" alt="Screenshot 2024-09-17 001733" src="https://github.com/user-attachments/assets/f2d86918-5b1b-4c7d-9b15-39f1231e2f7d">
<img width="374" alt="Screenshot 2024-09-17 001741" src="https://github.com/user-attachments/assets/af1a2e9d-bad8-4777-9859-ca9239222ee3">

2024-09-17 13:34 UTC, G4vp commented on src/App.js
Es este archivo necesario? Ya estas llamando <PauseScreen> en frontend/src/App.js

2024-09-17 16:19 UTC, fernandopizarro1 requested changes
I dont really think the `App.js` file is really necessary, since the frontend is the one that runs the game.

2024-09-17 23:25 UTC, Jvstinoo commented on src/App.js
Correcto, es un archivo viejo ya que habia clonado el repo antes de que se crearan los otros folders. Removido.

2024-09-17 23:27 UTC, Jvstinoo commented
> I dont really think the `scr/App.js` file is really necessary, since the game runs from the frontend folder.

That's right, it was an old file I forgot to remove since I cloned the repo a few weeks back when the other folders weren't created. Removed.

2024-09-18 17:12 UTC, fernandopizarro1 approved these changes
Nice job! LGTM

2024-09-18 17:27 UTC, AngelCIICMorales requested changes
Whenever you pause the game it resets the game.

2024-09-19 02:48 UTC, Jvstinoo commented
> Whenever you pause the game it resets the game.

Wasn't aware that was part of this issue. Added the functionality to save game while paused.

2024-09-19 12:18 UTC, AngelCIICMorales approved these changes
LGTM!

2024-09-19 12:19 UTC, merged