Add Authentication and Registration endpoints. Add dummy data to User…
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #113
Opened 2024-09-19 02:15 UTC by JadiellMV

Added Authentication and Registration endpoints, and also dummy data to the users table to be able to work with some data. This pull request was done collaboratively between @AnthonyMed13 and @JadiellMV, and takes care of task #24, task #18, and task #17.

2024-09-19 12:21 UTC, AngelCIICMorales requested changes
There is conflict. Please make sure the branch is up to date.

2024-09-19 23:37 UTC, FrancesC8 commented on package.json
> +{
The changes for this package.json should be in /backend/package.json.

2024-09-19 23:38 UTC, FrancesC8 commented on package-lock.json
> +{
This file should not exist here. There should only be package-lock.json files in the backend and frontend folders

2024-09-20 02:18 UTC, AnthonyMed13 commented
> There is conflict. Please make sure the branch is up to date.

Everything is up to date now

2024-09-20 12:34 UTC, AngelCIICMorales approved these changes
LGTM!

2024-09-20 12:59 UTC, AngelCIICMorales requested changes
Please fix the merge conflicts.

2024-09-20 15:31 UTC, sandy-marrero approved these changes

2024-09-20 15:36 UTC, AnthonyMed13 commented
> Please fix the merge conflicts.

Done.

2024-09-20 17:09 UTC, AngelCIICMorales approved these changes
LGTM.

2024-09-20 17:09 UTC, merged