156 - Screen to choose game mode.
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #208
Opened 2024-10-04 11:49 UTC by Jvstinoo

Created a placeholder screen to choose the game mode. After log in/sign up, it takes you to this screen so that you can choose the game mode.

At the moment the options are:

1. vs. AI: takes you to game against bot.
2. vs. player: takes you to lobby.

<img width="960" alt="Screenshot 2024-10-04 073756" src="https://github.com/user-attachments/assets/74ff586c-8e00-4481-bce2-e706322de6cc">

2024-10-04 12:47 UTC, fernandopizarro1 requested changes

2024-10-04 12:47 UTC, fernandopizarro1 commented on frontend/src/gameMode.js
Can you make it so that the player can choose between the different game modes in the Rule Engine? There is a dummy game mode there so you can use it even though it hasn't been completed yet.

2024-10-04 15:42 UTC, fernandopizarro1 approved these changes
LGTM

2024-10-04 15:42 UTC, fernandopizarro1 commented on frontend/src/gameMode.js
Nice. Thank you!

2024-10-06 12:53 UTC, AngelCIICMorales approved these changes
The game has an error message when entering the lobby and joining the game again. Fix this ASAP.

2024-10-06 12:54 UTC, merged

2024-10-06 12:56 UTC, fernandopizarro1 commented
> The game has an error message when entering the lobby and joining the game again. Fix this ASAP.

Can you elaborate further on this?

2024-10-06 14:09 UTC, Jvstinoo commented
> The game has an error message when entering the lobby and joining the game again. Fix this ASAP.

I see the issue, I'll create a PR for it later today. Should the game be saved when going back from lobby to the game or should it be a new game?

2024-10-06 14:13 UTC, fernandopizarro1 commented
> > The game has an error message when entering the lobby and joining the game again. Fix this ASAP.
> 
> I see the issue, I'll create a PR for it later today. Should the game be saved when going back from lobby to the game or should it be a new game?

Maybe we can put a warning that if the user goes to the lobby page, they will lose their progress and reset the game?