Adding Game Status to experimental game
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #212
Opened 2024-10-05 03:15 UTC by ilikecheese117

Added Game Status to experimental game as the saveGame function that updates game_status' variables every time a button is clicked on screen and then saves game_status to local storage so that data is not lost even in a refresh.

2024-10-05 18:15 UTC, fernandopizarro1 requested changes

2024-10-05 18:15 UTC, fernandopizarro1 commented on frontend/src/gamestate/experimentalGame.js
`const saveGame = () => {
        game_status.CurrentPlayer = currentTurn
        game_status.CurrentTable = tableData.TableState
        game_status.PlayerHands = playerData.PlayerHand
        game_status.Scores = 0
        localStorage.setItem('game_status_data', JSON.stringify(game_status));
        };`

It seems like the data is being saved correctly, but whenever the user refreshes the page or goes into the lobby page, the gamestatus refreshes anyways, maybe because everything else refreshes first. The gamestatus seems to be dependent on the data, and not the other way around.

2024-10-23 05:16 UTC, ilikecheese117 commented on frontend/src/gamestate/experimentalGame.js
So after pain for days now, the requested changes have, somewhat, happened. Let me respond back to this comment!

Right now, what you requested is more or less implemented. The only problem right now is that there is a visual glitch in that the matrix "resets" whenever you placed a domino after refreshing the page, but the player hand will remain the same regardless of refresh. This is because the Table class is not able to be serialized as a JSON string, which is required by JavaScript's LocalStorage (the class that saves changes across refreshes). The main issue that makes serialization of Table so hard is that it has both another class (the domino class) and class methods, which will be ignored when trying to stringify. I honestly tried to rework the Table class so that it could be appropriately stored as a JSON string to be retrieved by LocalStorage during refreshes and stop the glitch, but it's such a gigantean effort to do so that it could honestly be it's own issue for Milestone 3, and this pull request is already big enough without it. You might also noticed some other interesting changes in this pull request, which I will explain:
- I added the flatted package. This is due to the fact that playerData and tableData are circular structures (structures that end up referencing themselves in their fields somewhere along the way) and as such are not normally able to be serialized by JSON.serialize(). After searching through multiple packages, I ended up using Flatted and two of its functions were used to remedy this. It seems that a lot of the objects used in experimental game are circular structures. It might be worth it to wonder if this is a potential issue or not.
- I changed quotation marks for strings from single quotes to double quotes. This is due to the fact that it turns out that strings in single quotation quotes are not able to be serialized as only double quotes are recognized for JSON serialization. Some properties being like this 'property' ended up breaking the program when it came time to stringify. 
- Added some random comments and logs here and there for better tracking.

2024-10-23 13:16 UTC, fernandopizarro1 commented on frontend/src/gamestate/experimentalGame.js
The visual bug does not seem like a ginormous issue, but it should still be one that should be resolved, and it can be done for milestone 3 since it does not break the game entirely. As for everything else, it seems to run exaclty as you describe it, and it is true what you say about the gamestate since the gamestate would "technically" be the local storage. @AngelCIICMorales @Keiven-Soto what do you guys think about this?

2024-10-23 16:45 UTC, fernandopizarro1 commented on frontend/src/gamestate/experimentalGame.js
Can you save the bot data also? I noticed that the bot does not save its tiles

2024-10-23 19:45 UTC, ilikecheese117 commented on frontend/src/gamestate/experimentalGame.js
> Can you save the bot data also? I noticed that the bot does not save its tiles @ilikecheese117

I added everything in bot data that was not reliant on the table class to local storage. Also fixed a bug that causes the same game to keep going even if exited to lobby

2024-10-23 19:59 UTC, AngelCIICMorales requested changes
- The enemy player's tiles do not get saved.
- The board does not get saved.

2024-10-23 20:14 UTC, ilikecheese117 commented
> * The enemy player's tiles do not get saved.
> * The board does not get saved.

As I explained in a previous comment, the Table class, and by extension anything that depends on it, is not JSON serializable since it's both circular and many of its outputs are through methods rather than variables. This means it can't be saved to local storage without refactoring the entire table class. The change would be so big it might as well be its own issue for Milestone 3.

2024-10-23 20:31 UTC, ilikecheese117 commented
Everything that can be stored right now is being stored. To specify which items are being stored in local storage:
- BotHand
- DbHand
- TileCount
- DrawMatrix (Is later overwritten by Table, which can't be saved)
- PlayerHand
- DrawHand
- PlayerInput
- CurrentTurn

2024-10-25 18:48 UTC, fernandopizarro1 approved these changes

2024-10-25 22:38 UTC, AngelCIICMorales approved these changes
LGTM

2024-10-25 22:51 UTC, merged