Password Reset functionality added
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #264
Opened 2024-10-24 05:40 UTC by JadiellMV

Password Reset fully functional added, this would take care of task #136

2024-10-24 18:03 UTC, AngelCIICMorales requested changes
Fix the conflict.

2024-10-24 18:57 UTC, JadiellMV commented
Updated the ReadMe files for correct functionality of the feature:
-Run npm install nodemailer in the backend.
-Backend .env:
MONGODB_URI=mongodb://<yourUser>:<your userPassword>@localhost:27017/multiplayerDominoes
JWT_SECRET=23b3f7bb2c2993a97f8b13c96389939d2b9a0c69dbf836f4a79a7d1dd82aa2bc
PORT=8080
EMAIL_SERVICE=gmail
EMAIL_USER=multiplayerdominoes@gmail.com
EMAIL_PASSWORD=zdlsyxlsrbvltqsu
FRONTEND_URL=http://localhost:3000

-Frontend .env:
REACT_APP_BACKEND_URL=http://localhost:8080

2024-10-24 18:59 UTC, ebrain-mendoza121 approved these changes

2024-10-26 00:01 UTC, AngelCIICMorales approved these changes
LGTM

2024-10-26 00:01 UTC, merged