Incremented JWT security and fixed functionality
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #341
Opened 2024-11-06 18:00 UTC by JadiellMV

Fixed the current JWT usage to increment its security, not allowing it to be hardcoded, and also decremented the time it stays active for it to be more secure.

2024-11-08 13:41 UTC, AngelCIICMorales requested changes
abroad@LAPTOP-54IVI1AE:/mnt/c/Users/Angel/Desktop/Experiment/semester-project-multiplayer-dominoes/backend$ npm run dev

> semester-project-multiplayer-dominoes-server@1.0.0 dev
> nodemon src/index.js

[nodemon] 3.1.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node src/index.js`
file:///C:/Users/Angel/Desktop/Experiment/semester-project-multiplayer-dominoes/backend/src/index.js:12
    throw new Error('JWT_SECRET environment variable is required but not found.');
          ^

Error: JWT_SECRET environment variable is required but not found.
    at file:///C:/Users/Angel/Desktop/Experiment/semester-project-multiplayer-dominoes/backend/src/index.js:12:11        
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.0
[nodemon] app crashed - waiting for file changes before starting...

2024-11-11 01:49 UTC, JadiellMV commented
@AngelCIICMorales you should have JWT_SECRET=23b3f7bb2c2993a97f8b13c96389939d2b9a0c69dbf836f4a79a7d1dd82aa2bc in the .env file for it to work

2024-11-11 01:56 UTC, AngelCIICMorales approved these changes
LGTM

2024-11-11 02:01 UTC, ebrain-mendoza121 approved these changes

2024-11-11 02:10 UTC, merged