Created backend skeleton
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #72
Opened 2024-09-04 08:10 UTC by FrancesC8

This contains the backend skeleton using the discussed technologies in the past. The initial skeleton is creates an Express application in Node.js with connection to MongoDB **locally**. The backend `README.md` contains all the information with a small project overview and steps on how to setup your local environment to run the project locally.

Additionally, it contains some predefined code structure with examples by following the Model/Handler/Controller structure, see the `backend/README.md` for further details.

Lastly, I separated the frontend and backend files to have everything in one place in a more clean way.

2024-09-07 17:20 UTC, AngelCIICMorales requested changes
It works. However, the read me should be improved in order to clarify certain aspects of the process.

2024-09-07 18:43 UTC, FrancesC8 commented
> It works. However, the read me should be improved in order to clarify certain aspects of the process.

I'll update it. Thanks!

2024-09-09 01:41 UTC, Keiven-Soto approved these changes

2024-09-09 01:56 UTC, AngelCIICMorales approved these changes
Everything is working correctly.

2024-09-09 01:57 UTC, merged