Initial login/signup form implementation
uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes pull request #99
Opened 2024-09-14 21:06 UTC by sandy-marrero

Pull request for issue #21, initial login/signup form on the frontend has been made and aligned with #60. It is missing the functionality as work is still being worked on for the login/signup endpoints. Closes #21 

![Screenshot 2024-09-14 164844](https://github.com/user-attachments/assets/27ac460f-d6a1-4de4-be97-78ef39a3212c)
![Screenshot 2024-09-14 164838](https://github.com/user-attachments/assets/20e02dc6-1e37-416d-87ed-19194dd952fd)

2024-09-14 22:57 UTC, AngelCIICMorales requested changes
I see no change from the main branch. I noticed that the file changes are not reflected when booting up the webapp.

2024-09-14 23:40 UTC, sandy-marrero commented
> I see no change from the main branch. I noticed that the file changes are not reflected when booting up the webapp.

Updated so it makes the login/signup page the landing page. It does not validate for actual accounts yet so it should lead to the gamestate directly. Login -> GameState. 

Made some additional CSS changes and merged the branch with the latest changes on main.

2024-09-15 22:14 UTC, AngelCIICMorales approved these changes
Lgtm.

2024-09-16 00:28 UTC, Keiven-Soto approved these changes

2024-09-16 00:28 UTC, merged